import { NextResponse } from "next/server"

// Mock game data for demonstration
const mockGames = [
  {
    GameTitle: { S: "Snake" },
    YearDeveloped: { S: "1997" },
    Developer: { S: "Nokia" },
    City: { S: "Espoo" },
    DeveloperLocation: { S: "Finland" },
    GameWebsite: { S: "https://example.com" },
    GameDescription: {
      S: "Classic snake game where you control a growing line that must avoid hitting walls or itself.",
    },
    Photos: { S: "/retro-snake-game.jpg" },
    Videos: { S: "" },
    Articles: { S: "" },
    Purpose: { S: "Entertainment" },
    OpenSource: { S: "No" },
    Players: { S: "1" },
    SiteSpecific: { S: "No" },
    Genre: { S: "Arcade, Puzzle" },
    HardwareFeatures: { S: "Nokia 6110" },
    Connectivity: { S: "None" },
    Contact: { S: "N/A" },
  },
  {
    GameTitle: { S: "Tetris" },
    YearDeveloped: { S: "1989" },
    Developer: { S: "Nintendo" },
    City: { S: "Kyoto" },
    DeveloperLocation: { S: "Japan" },
    GameWebsite: { S: "https://example.com" },
    GameDescription: { S: "Iconic puzzle game where players arrange falling blocks to create complete lines." },
    Photos: { S: "/game-boy-tetris.jpg" },
    Videos: { S: "" },
    Articles: { S: "" },
    Purpose: { S: "Entertainment" },
    OpenSource: { S: "No" },
    Players: { S: "1-2" },
    SiteSpecific: { S: "No" },
    Genre: { S: "Puzzle" },
    HardwareFeatures: { S: "Game Boy" },
    Connectivity: { S: "Link Cable" },
    Contact: { S: "N/A" },
  },
  {
    GameTitle: { S: "Space Impact" },
    YearDeveloped: { S: "1999" },
    Developer: { S: "Nokia" },
    City: { S: "Espoo" },
    DeveloperLocation: { S: "Finland" },
    GameWebsite: { S: "https://example.com" },
    GameDescription: { S: "Side-scrolling shooter game pre-installed on Nokia mobile phones." },
    Photos: { S: "/space-impact-nokia-game.jpg" },
    Videos: { S: "" },
    Articles: { S: "" },
    Purpose: { S: "Entertainment" },
    OpenSource: { S: "No" },
    Players: { S: "1" },
    SiteSpecific: { S: "No" },
    Genre: { S: "Action, Shooter" },
    HardwareFeatures: { S: "Nokia 3310" },
    Connectivity: { S: "None" },
    Contact: { S: "N/A" },
  },
  {
    GameTitle: { S: "Pokemon Red" },
    YearDeveloped: { S: "1996" },
    Developer: { S: "Game Freak" },
    City: { S: "Tokyo" },
    DeveloperLocation: { S: "Japan" },
    GameWebsite: { S: "https://example.com" },
    GameDescription: { S: "RPG adventure where players catch and train creatures called Pokemon." },
    Photos: { S: "/pokemon-red-game-boy.jpg" },
    Videos: { S: "" },
    Articles: { S: "" },
    Purpose: { S: "Entertainment" },
    OpenSource: { S: "No" },
    Players: { S: "1-2" },
    SiteSpecific: { S: "No" },
    Genre: { S: "RPG, Adventure" },
    HardwareFeatures: { S: "Game Boy" },
    Connectivity: { S: "Link Cable" },
    Contact: { S: "N/A" },
  },
  {
    GameTitle: { S: "Bounce" },
    YearDeveloped: { S: "2000" },
    Developer: { S: "Nokia" },
    City: { S: "Espoo" },
    DeveloperLocation: { S: "Finland" },
    GameWebsite: { S: "https://example.com" },
    GameDescription: { S: "Platform game featuring a red ball navigating through various levels." },
    Photos: { S: "/bounce-nokia-game.jpg" },
    Videos: { S: "" },
    Articles: { S: "" },
    Purpose: { S: "Entertainment" },
    OpenSource: { S: "No" },
    Players: { S: "1" },
    SiteSpecific: { S: "No" },
    Genre: { S: "Platform, Action" },
    HardwareFeatures: { S: "Nokia 6110" },
    Connectivity: { S: "None" },
    Contact: { S: "N/A" },
  },
  {
    GameTitle: { S: "Super Mario Land" },
    YearDeveloped: { S: "1989" },
    Developer: { S: "Nintendo" },
    City: { S: "Kyoto" },
    DeveloperLocation: { S: "Japan" },
    GameWebsite: { S: "https://example.com" },
    GameDescription: { S: "Classic platformer featuring Mario in the Sarasaland kingdom." },
    Photos: { S: "/super-mario-land-game-boy.jpg" },
    Videos: { S: "" },
    Articles: { S: "" },
    Purpose: { S: "Entertainment" },
    OpenSource: { S: "No" },
    Players: { S: "1" },
    SiteSpecific: { S: "No" },
    Genre: { S: "Platform, Action" },
    HardwareFeatures: { S: "Game Boy" },
    Connectivity: { S: "None" },
    Contact: { S: "N/A" },
  },
  {
    GameTitle: { S: "Worms World Party" },
    YearDeveloped: { S: "2001" },
    Developer: { S: "Team17" },
    City: { S: "Wakefield" },
    DeveloperLocation: { S: "United Kingdom" },
    GameWebsite: { S: "https://example.com" },
    GameDescription: { S: "Turn-based strategy game featuring teams of worms battling with various weapons." },
    Photos: { S: "/worms-mobile-game.jpg" },
    Videos: { S: "" },
    Articles: { S: "" },
    Purpose: { S: "Entertainment" },
    OpenSource: { S: "No" },
    Players: { S: "1-4" },
    SiteSpecific: { S: "No" },
    Genre: { S: "Strategy, Action" },
    HardwareFeatures: { S: "Nokia N-Gage" },
    Connectivity: { S: "Bluetooth" },
    Contact: { S: "N/A" },
  },
  {
    GameTitle: { S: "Sonic Advance" },
    YearDeveloped: { S: "2001" },
    Developer: { S: "Sonic Team" },
    City: { S: "Tokyo" },
    DeveloperLocation: { S: "Japan" },
    GameWebsite: { S: "https://example.com" },
    GameDescription: { S: "Fast-paced platformer featuring Sonic the Hedgehog on Game Boy Advance." },
    Photos: { S: "/sonic-advance-gba.jpg" },
    Videos: { S: "" },
    Articles: { S: "" },
    Purpose: { S: "Entertainment" },
    OpenSource: { S: "No" },
    Players: { S: "1-4" },
    SiteSpecific: { S: "No" },
    Genre: { S: "Platform, Action" },
    HardwareFeatures: { S: "Game Boy Advance" },
    Connectivity: { S: "Link Cable" },
    Contact: { S: "N/A" },
  },
  {
    GameTitle: { S: "Bejeweled" },
    YearDeveloped: { S: "2001" },
    Developer: { S: "PopCap Games" },
    City: { S: "Seattle" },
    DeveloperLocation: { S: "United States" },
    GameWebsite: { S: "https://example.com" },
    GameDescription: { S: "Match-3 puzzle game where players swap gems to create lines of three or more." },
    Photos: { S: "/bejeweled-mobile-game.jpg" },
    Videos: { S: "" },
    Articles: { S: "" },
    Purpose: { S: "Entertainment" },
    OpenSource: { S: "No" },
    Players: { S: "1" },
    SiteSpecific: { S: "No" },
    Genre: { S: "Puzzle" },
    HardwareFeatures: { S: "Palm Pilot" },
    Connectivity: { S: "None" },
    Contact: { S: "N/A" },
  },
  {
    GameTitle: { S: "Doom RPG" },
    YearDeveloped: { S: "2005" },
    Developer: { S: "id Software" },
    City: { S: "Dallas" },
    DeveloperLocation: { S: "United States" },
    GameWebsite: { S: "https://example.com" },
    GameDescription: { S: "Turn-based RPG adaptation of the classic first-person shooter for mobile phones." },
    Photos: { S: "/doom-rpg-mobile.jpg" },
    Videos: { S: "" },
    Articles: { S: "" },
    Purpose: { S: "Entertainment" },
    OpenSource: { S: "No" },
    Players: { S: "1" },
    SiteSpecific: { S: "No" },
    Genre: { S: "RPG, Action" },
    HardwareFeatures: { S: "Java Phone" },
    Connectivity: { S: "None" },
    Contact: { S: "N/A" },
  },
  {
    GameTitle: { S: "Diner Dash" },
    YearDeveloped: { S: "2005" },
    Developer: { S: "PlayFirst" },
    City: { S: "San Francisco" },
    DeveloperLocation: { S: "United States" },
    GameWebsite: { S: "https://example.com" },
    GameDescription: { S: "Time management game where players help Flo serve customers in her restaurant." },
    Photos: { S: "/diner-dash-mobile.jpg" },
    Videos: { S: "" },
    Articles: { S: "" },
    Purpose: { S: "Entertainment" },
    OpenSource: { S: "No" },
    Players: { S: "1" },
    SiteSpecific: { S: "No" },
    Genre: { S: "Strategy, Casual" },
    HardwareFeatures: { S: "Java Phone" },
    Connectivity: { S: "None" },
    Contact: { S: "N/A" },
  },
  {
    GameTitle: { S: "Asphalt Urban GT" },
    YearDeveloped: { S: "2004" },
    Developer: { S: "Gameloft" },
    City: { S: "Paris" },
    DeveloperLocation: { S: "France" },
    GameWebsite: { S: "https://example.com" },
    GameDescription: { S: "Racing game featuring exotic cars and urban street racing." },
    Photos: { S: "/asphalt-urban-gt-mobile.jpg" },
    Videos: { S: "" },
    Articles: { S: "" },
    Purpose: { S: "Entertainment" },
    OpenSource: { S: "No" },
    Players: { S: "1-4" },
    SiteSpecific: { S: "No" },
    Genre: { S: "Racing, Sports" },
    HardwareFeatures: { S: "Nokia N-Gage" },
    Connectivity: { S: "Bluetooth" },
    Contact: { S: "N/A" },
  },
]

export async function GET() {
  // Simulate API delay
  await new Promise((resolve) => setTimeout(resolve, 500))

  return NextResponse.json(mockGames)
}
