export interface Publication {
  id: number
  title: string
  authors: string[]
  year: number
  description: string
  thumbnail: string
  categories: string[]
  topic: string
  link?: string
}

export const publicationsData: Publication[] = [
  {
    id: 1,
    title: "Infrastructures Enabling Creativity and Play in Hybrid Spaces",
    authors: ["Glover, R"],
    year: 2024,
    description: "Glover, R. (2024). Infrastructures Enabling Creativity and Play in Hybrid Spaces. In The Mobile Media Debate (pp. 130-142). Routledge.",
    thumbnail: "/mobile-gaming-interface.jpg",
    categories: ["Articles", "Hybrid Spaces"],
    topic: "Hybrid Spaces",
  },
  {
    id: 2,
    title: "Playful mobilities in the Global South: A study of Pokémon Go play in Rio de Janeiro and Nairobi",
    authors: ["de Souza e Silva, A.", "Glover-Rijkse, R.", "Njathi, A.", "de Cunto Bueno, D."],
    year: 2023,
    description: "de Souza e Silva, A., Glover-Rijkse, R., Njathi, A., & de Cunto Bueno, D. (2023). Playful mobilities in the Global South: A study of Pokémon Go play in Rio de Janeiro and Nairobi. New Media & Society, 25(5), 963-979.",
    thumbnail: "/nokia-snake-game.jpg",
    categories: ["Articles", "Global South", "Mobile Games"],
    topic: "Cultural Studies",
  },
  {
    id: 3,
    title: "Software Presentation: The Retro Mobile Gaming Database",
    authors: ["de Souza e Silva, A.", "Glover-Rijkse, R."],
    year: 2023,
    description: "de Souza e Silva, A., & Glover-Rijkse, R. (2023). Software Presentation: The Retro Mobile Gaming Database. Mobile Media & Communication, 1–6.",
    thumbnail: "/preservation-archiving.jpg",
    categories: ["Articles", "Database", "Preservation"],
    topic: "Preservation",
  },
  {
    id: 4,
    title: "Preserving the History of Mobile Gaming: A review of the Retro Mobile Gaming Database",
    authors: ["Frith, J."],
    year: 2023,
    description: "Frith, J. (2023). Preserving the History of Mobile Gaming: A review of the Retro Mobile Gaming Database. Mobile Media & Communication.",
    thumbnail: "/gaming-historian.jpg",
    categories: ["Articles", "Review", "Preservation"],
    topic: "Preservation",
  },
  {
    id: 5,
    title: "Exploring the material conditions of Pokémon Go play in Rio de Janeiro and Nairobi",
    authors: ["de Souza e Silva, A.", "Glover-Rijkse, R.", "Njathi, A.", "de Cunto Bueno, D."],
    year: 2021,
    description: "de Souza e Silva, A., Glover-Rijkse, R., Njathi, A., & de Cunto Bueno, D. (2021). Exploring the material conditions of Pokémon Go play in Rio de Janeiro and Nairobi. Information, Communication & Society, 24(6), 813-829.",
    thumbnail: "/multiplayer-games.jpg",
    categories: ["Articles", "Materiality", "Global South"],
    topic: "Cultural Studies",
  },
  {
    id: 6,
    title: "A dialogue with Nick Tandavanitj from Blast Theory",
    authors: ["Glover-Rijkse, R."],
    year: 2020,
    description: "Glover-Rijkse, R. (2020). A dialogue with Nick Tandavanitj from Blast Theory. Hybrid Play: Crossing Boundaries in Game Design, Players Identities and Play Spaces.",
    thumbnail: "/audio-design-gaming.jpg",
    categories: ["Articles", "Game Design"],
    topic: "Game Design",
  },
  {
    id: 7,
    title: "Hybrid play: Crossing boundaries in game design, players identities and play spaces",
    authors: ["de Souza e Silva, A.", "Glover-Rijkse, R."],
    year: 2020,
    description: "e Souza e Silva, A., & Glover-Rijkse, R. (Eds.). (2020). Hybrid play: Crossing boundaries in game design, players identities and play spaces. Routledge.",
    thumbnail: "/game-boy-tetris.jpg",
    categories: ["Articles", "Hybrid Play"],
    topic: "Hybrid Play",
  },
  {
    id: 8,
    title: "Historicizing Hybrid Spaces in Mobile Media Art",
    authors: ["e Souza e Silva, A.", "Glover-Rijkse, R."],
    year: 2020,
    description: "e Souza e Silva, A., & Glover-Rijkse, R. (2020). Historicizing Hybrid Spaces in Mobile Media Art. In The Routledge Companion to Mobile Media Art (pp. 117-127). Routledge.",
    thumbnail: "/mobile-gaming-interface.jpg",
    categories: ["Articles", "Media Art", "History"],
    topic: "History",
  },
  {
    id: 9,
    title: "Location-based mobile games: Interfaces to urban spaces",
    authors: ["de Souza e Silva, A.", "Frith, J."],
    year: 2015,
    description: "de Souza e Silva, A., & Frith, J. (2015). Location-based mobile games: Interfaces to urban spaces. In V. Frissen (Ed.), Playful Identities: The Ludification of Digital Media Cultures.",
    thumbnail: "/nokia-snake-game.jpg",
    categories: ["Book Chapter", "Urban Spaces"],
    topic: "Urban Spaces",
  },
  {
    id: 10,
    title: "Playful Urban Spaces: A historical approach to mobile games",
    authors: ["de Souza e Silva, A.", "Hjorth, L."],
    year: 2009,
    description: "de Souza e Silva, A., & Hjorth, L. (2009). Playful Urban Spaces: A historical approach to mobile games. Simulation & Gaming, 40(5).",
    thumbnail: "/preservation-archiving.jpg",
    categories: ["Articles", "Urban Spaces", "History"],
    topic: "History",
  },
  {
    id: 11,
    title: "Hybrid Reality and Location-Based Gaming: Redefining mobility and game spaces in urban environments",
    authors: ["de Souza e Silva, A."],
    year: 2009,
    description: "de Souza e Silva, A. (2009). Hybrid Reality and Location-Based Gaming: Redefining mobility and game spaces in urban environments. Simulation & Gaming, 40(3), 404–424.",
    thumbnail: "/multiplayer-games.jpg",
    categories: ["Articles", "Hybrid Reality"],
    topic: "Hybrid Reality",
  },
  {
    id: 12,
    title: "Alien Revolt (2005–2007): A case study of the first location-based mobile game in Brazil",
    authors: ["de Souza e Silva, A."],
    year: 2008,
    description: "de Souza e Silva, A. (2008). Alien Revolt (2005–2007): A case study of the first location-based mobile game in Brazil. IEEE Technology and Society Magazine, 27(1), 18–28.",
    thumbnail: "/game-boy-tetris.jpg",
    categories: ["Articles", "Case Study"],
    topic: "Case Study",
  },
  {
    id: 13,
    title: "Conceptualizing locative social mobile networks",
    authors: ["de Souza e Silva, A."],
    year: 2007,
    description: "de Souza e Silva, A. (2007, Oct.). Conceptualizing locative social mobile networks: Smart mobs, location-based games and interpersonal-aware applications. AoIR 2007.",
    thumbnail: "/audio-design-gaming.jpg",
    categories: ["Conference Paper", "Social Networks"],
    topic: "Social Networks",
  },
]